import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import type { Project, ProjectStatus } from '@/domain/types';
import type { ProjectInput } from '@/integrations/local/project-store';
import { useProjects } from '@/app/providers/use-projects';
import { useFeedPosts } from '@/app/providers/use-feed-posts';
import { PostCard } from '@/components/feed/PostCard';
import { ProjectAvatar } from '@/components/ui/ProjectAvatar';
import { Button } from '@/components/ui/Button';
import { ROUTES } from '@/config/constants';

const EMPTY: ProjectInput = { name: '', description: '', category: '', technology: '', status: 'in-progress' };
const STATUS_LABELS: Record<ProjectStatus, string> = { 'in-progress': 'In Progress', 'on-hold': 'On Hold', completed: 'Completed' };

function ProjectForm({ initial, onSave, onClose }: { initial?: Project; onSave: (input: ProjectInput) => Promise<void>; onClose: () => void }) {
 const [form, setForm] = useState<ProjectInput>(initial ? { name: initial.name, description: initial.description ?? '', category: initial.category, technology: initial.technology ?? '', status: initial.status } : EMPTY);
 const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
 const update = (key: 'name' | 'description' | 'category' | 'technology', value: string) => setForm((current) => ({ ...current, [key]: value }));
 async function save() { if (!form.name.trim() || !form.category.trim()) { setError('Add a project name and category.'); return; } setSaving(true); try { await onSave(form); onClose(); } catch { setError('Could not save this project locally.'); } finally { setSaving(false); } }
 return <div className="fixed inset-0 z-50 flex items-end justify-center bg-scrim md:items-center md:p-6" role="dialog" aria-modal="true" aria-label={initial ? 'Edit project' : 'New project'}><div className="panel-solid max-h-[95dvh] w-full max-w-2xl overflow-y-auto rounded-t-2xl border p-5 md:rounded-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-headline-sm font-bold">{initial ? 'Edit Project' : 'New Project'}</h2><button type="button" onClick={onClose} aria-label="Close project form" className="text-2xl text-text-muted">×</button></div><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1 block text-label-md">Project name</span><input autoFocus value={form.name} onChange={(e) => update('name', e.target.value)} className="h-11 w-full rounded-xl border border-border-subtle bg-surface px-3" /></label><label className="sm:col-span-2"><span className="mb-1 block text-label-md">Short description</span><textarea rows={3} value={form.description} onChange={(e) => update('description', e.target.value)} className="w-full rounded-xl border border-border-subtle bg-surface px-3 py-2" /></label><label><span className="mb-1 block text-label-md">Category / craft</span><input value={form.category} onChange={(e) => update('category', e.target.value)} placeholder="Game development" className="h-11 w-full rounded-xl border border-border-subtle bg-surface px-3" /></label><label><span className="mb-1 block text-label-md">Technology / tool</span><input value={form.technology} onChange={(e) => update('technology', e.target.value)} placeholder="Optional" className="h-11 w-full rounded-xl border border-border-subtle bg-surface px-3" /></label><label><span className="mb-1 block text-label-md">Status</span><select value={form.status} onChange={(e) => setForm((current) => ({ ...current, status: e.target.value as ProjectStatus }))} className="h-11 w-full rounded-xl border border-border-subtle bg-surface px-3">{Object.entries(STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span className="mb-1 block text-label-md">Project icon</span><input type="file" accept="image/*" onChange={(e) => setForm((c) => ({ ...c, avatarFile: e.target.files?.[0] }))} className="block w-full text-caption" /></label><label className="sm:col-span-2"><span className="mb-1 block text-label-md">Cover image</span><input type="file" accept="image/*" onChange={(e) => setForm((c) => ({ ...c, coverFile: e.target.files?.[0] }))} className="block w-full text-caption" /></label></div>{error ? <p className="mt-4 text-body-sm text-error">{error}</p> : null}<div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="button" disabled={saving} onClick={() => void save()}>{saving ? 'Saving…' : initial ? 'Save Changes' : 'Create Project'}</Button></div></div></div>;
}

function ProjectList({ onCreate }: { onCreate: () => void }) { const { projects, isLoading } = useProjects(); return <div><div className="mb-6 flex items-center justify-between"><div><h1 className="text-headline-md font-bold">My Projects</h1><p className="mt-1 text-body-md text-text-muted">Projects are saved locally in this browser.</p></div><Button onClick={onCreate}>New Project</Button></div>{isLoading ? <p className="py-12 text-center text-text-muted">Loading projects…</p> : projects.length ? <div className="grid gap-4 sm:grid-cols-2">{projects.map((project) => <Link key={project.id} to={ROUTES.project(project.id)} className="glass-card glass-card-hover rounded-xl border p-4"><div className="flex gap-3"><ProjectAvatar initial={project.name[0] ?? 'P'} avatarUrl={project.avatarUrl} /><div className="min-w-0"><h2 className="truncate text-label-lg font-bold">{project.name}</h2><p className="mt-1 line-clamp-2 text-body-sm text-text-muted">{project.description || 'No description yet.'}</p><div className="mt-3 flex flex-wrap gap-2 text-caption"><span>{project.category}</span><span className="text-primary">{STATUS_LABELS[project.status]}</span></div><p className="mt-2 text-caption text-text-faint">Updated {new Date(project.updatedAt).toLocaleDateString()}</p></div></div></Link>)}</div> : <div className="rounded-2xl border border-dashed border-border-default px-6 py-16 text-center"><ProjectAvatar initial="P" /><h2 className="mt-4 text-headline-sm font-bold">Start something worth sharing</h2><p className="mx-auto mt-2 max-w-sm text-body-md text-text-muted">Create your first project and keep its progress, updates, and history together.</p><Button className="mt-5" onClick={onCreate}>Create Project</Button></div>}</div>; }

function ProjectDetail({ project, onEdit, onDelete }: { project: Project; onEdit: () => void; onDelete: () => void }) { const { posts } = useFeedPosts(); const timeline = posts.filter((post) => post.project?.id === project.id); return <div><Link to={ROUTES.projects} className="text-label-md text-text-muted hover:text-primary">← My Projects</Link>{project.coverUrl ? <img src={project.coverUrl} alt="" className="mt-4 h-40 w-full rounded-2xl object-cover" /> : null}<header className="mt-5 flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><ProjectAvatar initial={project.name[0] ?? 'P'} avatarUrl={project.avatarUrl} size="md" /><div><h1 className="text-headline-md font-bold">{project.name}</h1><p className="mt-1 text-body-md text-text-secondary">{project.description || 'No description yet.'}</p><div className="mt-3 flex flex-wrap gap-2 text-caption text-text-muted"><span>{project.category}</span>{project.technology ? <span>· {project.technology}</span> : null}<span>· {STATUS_LABELS[project.status]}</span></div></div></div><div className="flex gap-2"><Button variant="secondary" onClick={onEdit}>Edit Project</Button><Button variant="secondary" onClick={onDelete}>Delete</Button></div></header><section className="mt-8"><h2 className="mb-4 text-headline-sm font-bold">Project history</h2>{timeline.length ? <div className="flex flex-col gap-5">{timeline.map((post) => <PostCard key={post.id} post={post} />)}</div> : <p className="rounded-xl border border-dashed border-border-default px-5 py-10 text-center text-body-md text-text-muted">No updates yet. Link a new post to this project to start its history.</p>}</section></div>; }

export function ProjectsPage() { const { projectId } = useParams(); const navigate = useNavigate(); const { projects, createProject, updateProject, deleteProject } = useProjects(); const project = projectId ? projects.find((item) => item.id === projectId) : undefined; const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Project>(); useEffect(() => { if (projectId && projects.length && !project) navigate(ROUTES.projects, { replace: true }); }, [projectId, projects, project, navigate]); function openCreate() { setEditing(undefined); setFormOpen(true); } if (projectId && project) return <><ProjectDetail project={project} onEdit={() => { setEditing(project); setFormOpen(true); }} onDelete={() => { if (window.confirm(`Delete ${project.name}? Its posts will remain in the feed.`)) void deleteProject(project.id).then(() => navigate(ROUTES.projects)); }} />{formOpen ? <ProjectForm initial={editing} onClose={() => setFormOpen(false)} onSave={(input) => updateProject(project.id, input).then(() => undefined)} /> : null}</>; return <><ProjectList onCreate={openCreate} />{formOpen ? <ProjectForm onClose={() => setFormOpen(false)} onSave={(input) => createProject(input).then(() => undefined)} /> : null}</>; }
